name: UnitedItems
version: '${project.version}'
main: org.unitedlands.items.UnitedItems
api-version: 1.17
authors: [ Maroon28 ]
contributors: [ Litning11, Theriel_ ]
depend: [NBTAPI, Towny, ItemsAdder]
commands:
  tree:
    description: Main tree command